### ISSUE TITLE
Problem adding bulma with svelte-add

### ISSUE THREAD

**Issue by Samu01Tech** [svelte-add/bulma#3] opened 2021-04-26 08:21 UTC
# The problem
Using the command:
```bash
npx svelte-add bulma
```

gives this error:

```bash
UnhandledPromiseRejectionWarning: Error: Unknown variable dynamic import: ./adders/bulma/run.js

...

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the 
CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

# How to solve
Use this command: 

```bash
npx svelte-add svelte-add/bulma
```

_comment_: maybe it is not a problem, i'm not an expert but this might help others like me.

**Comment by manuel3108** [comment] 2021-04-26 19:26
I just tried this now, and could not reproduce it. When did you tried to use this template? 

Might this be related to https://github.com/svelte-add/svelte-add/issues/26?

**Comment by nitroboy720** [comment] 2021-05-06 19:45
I ran into same issue, your solution worked for me.

**Comment by yanagi-tarou** [comment] 2021-05-07 01:59
Try this one. I avoided the error.
```
$ npx svelte-add@2021.4.1-9.0 svelte-add/bulma
```

**Comment by manuel3108** [comment] 2021-05-09 11:20
Hey is this still happening for you?
I just tried it right now, but for me everything worked seamlessly without adding any version suffix to svelte-add

**Comment by babichjacob** [comment] 2021-05-11 14:08
This is my mistake. It'll be fixed when I can.

**Comment by manuel3108** [comment] 2021-06-11 13:41
@yanagi-tarou @Samu01Tech  @nitroboy720  Can you maybe confirm which node-version you are running? I'm currently guessing you are on node 12. If so this could be related to https://github.com/svelte-add/svelte-add/issues/41

**Comment by manuel3108** [comment] 2021-09-18 07:09
I think @babichjacob already fixed this issue long time ago. Closing here

**Closed by manuel3108** 2021-09-18 07:09 UTC
Labels: bug
